volume-cleanup:
  scale: 1
  labels:
    io.rancher.scheduler.global: 'true'
drone-army-01:
  scale: 1
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.drone.role=follower
drone-master:
  scale: 1
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.drone.role=master
